spring:
  # 데이터베이스 접속정보 설정
  datasource:
    username: salondebebe
    password: akaskqrhOK2!
    url: jdbc:mariadb://salondebebe.cafe24.com:3306/salondebebe
    driver-class-name: org.mariadb.jdbc.Driver
  # 타임리프 설정
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      location: /fileupload
      max-request-size: 50MB 
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
 
mybatis:
  mapper-locations:
  - classpath:config/mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
    
logging:
  config: classpath:config/logback.xml
    
# 파일 환경설정 정보
file:
  root-path: /fileupload
  
jwt:
  secret-key: asdfcdsr432rsdcsdfsdfdsfsdfsfdfcds